### ISSUE TITLE
Host player doesn't load

### ISSUE THREAD

**Issue by LucasFASouza** [devmoreir4/godot-3d-multiplayer-template#2]
When the first player click in host, so others can join, their screen just goes gray, and they aren't load in the scene.
I don't know if I'm doing something wrong or if that's the expected outcome.

I tested locally only and didn't change the ip address.

**Comment by rosieposieeee** [comment]
this happens for me as well, and i even checked that the host was being counted among the players connected - they are.

**Comment by devmoreir4** [comment]
To run the project, make sure you are using Godot Engine 4.3. Additionally, you need to select the number of instances that will be executed when starting the project (this works as a debug mode simulating client connections).

So, before running the project, you should select the Debug option and set the number of clients that will connect (I left a note about this in the repository's readme).

The gray screen you mentioned is the host's screen, as the `camera.current` is disabled. I left it this way because the host is not treated as a player in this template, but if you want the host to be a player, you can make a few simple changes, as well as remove some if statements.

Hope this helps.

**Comment by LucasFASouza** [comment]
Got it! I did use godot 4.3, select the number of intances and everything, but I didn't know that the host isn't considered a player in the template. Thank you.
